[package]
name = "ls"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
wit-bindgen = "0.20.0"

[package.metadata.component]
package = "commander:base"
