[workspace]

members = [
    "commander-engine",
    "host",
    "example-programs/mastodon-feed",
    "commander-ui/src-tauri",
    "core-programs/ls",
    "core-programs/file-explorer",
]
exclude = ["program_template"]
