[package]
name = "file-explorer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.80"
wit-bindgen = "0.20.0"

[package.metadata.component]
package = "commander:base"
